steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/angular-app:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/angular-app:latest'


images:
  - 'gcr.io/$PROJECT_ID/angular-app:latest'


options:
  logging: CLOUD_LOGGING_ONLY


